#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  May 17, 2022 11:14:17 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m48" -background #0433d5 
    wm focusmodel $top passive
    wm geometry $top 1366x705+408+112
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab46 \
        -borderwidth 0 \
        -font {-family {Nirmala UI Semilight} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #9dc9f4 -text {Tally Prime} -background #0433d5 \
        -height 65 -width 1380 
    vTcl:DefineAlias "$top.lab46" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab46
    label $site_3_0.lab80 \
        -activeforeground SystemButtonText -anchor w -background #0433d5 \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family Tahoma -size 17 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #c0b73f -text GOLD 
    vTcl:DefineAlias "$site_3_0.lab80" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activeforeground SystemButtonText -anchor w -background #0433d5 \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 8 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #55d1e8 -text MANAGE 
    vTcl:DefineAlias "$site_3_0.lab81" "Label8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text K:Company 
    vTcl:DefineAlias "$site_3_0.but82" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433D5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Y:Data 
    vTcl:DefineAlias "$site_3_0.but83" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433D5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Z:Exchange 
    vTcl:DefineAlias "$site_3_0.but84" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {G:Go To} 
    vTcl:DefineAlias "$site_3_0.but85" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text O:Import 
    vTcl:DefineAlias "$site_3_0.but86" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text E:Export 
    vTcl:DefineAlias "$site_3_0.but87" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text M:E-mail 
    vTcl:DefineAlias "$site_3_0.but88" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text P:Print 
    vTcl:DefineAlias "$site_3_0.but89" "Button8" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #0433d5 -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text F1:Help 
    vTcl:DefineAlias "$site_3_0.but90" "Button9" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab80 \
        -in $site_3_0 -x 0 -y 0 -rely 0.308 -width 0 -relwidth 0.053 \
        -height 0 -relheight 0.477 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.093 -y 0 -width 0 -relwidth 0.062 \
        -height 0 -relheight 0.477 -anchor nw -bordermode ignore 
    place $site_3_0.but82 \
        -in $site_3_0 -x 0 -relx 0.093 -y 0 -rely 0.462 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but83 \
        -in $site_3_0 -x 0 -relx 0.203 -y 0 -rely 0.462 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but84 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.462 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but85 \
        -in $site_3_0 -x 0 -relx 0.406 -y 0 -rely 0.462 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but86 \
        -in $site_3_0 -x 0 -relx 0.616 -y 0 -rely 0.462 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but87 \
        -in $site_3_0 -x 0 -relx 0.681 -y 0 -rely 0.462 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but88 \
        -in $site_3_0 -x 0 -relx 0.739 -y 0 -rely 0.462 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but89 \
        -in $site_3_0 -x 0 -relx 0.812 -y 0 -rely 0.462 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but90 \
        -in $site_3_0 -x 0 -relx 0.87 -y 0 -rely 0.462 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background #9dc9f4 -height 24 \
        -width 1387 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    frame $site_3_0.fra49 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -width 125 
    vTcl:DefineAlias "$site_3_0.fra49" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activeforeground SystemButtonText -anchor w -background #9dc9f4 \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 7 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Gateway of Tally} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra49 \
        -in $site_3_0 -x 0 -relx 0.916 -y 0 -rely 6 -width 0 -relwidth 0.092 \
        -height 0 -relheight 5 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely -0.583 -width 0 \
        -relwidth 0.087 -height 0 -relheight 2.125 -anchor nw \
        -bordermode ignore 
    menu $top.m48 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background #ffffff -font TkMenuFont \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background #d9ffff -height 633 \
        -width 158 
    vTcl:DefineAlias "$top.fra50" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra50
    button $site_3_0.but91 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound center \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -pady 0 -text F2:Date 
    vTcl:DefineAlias "$site_3_0.but91" "Button10" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but92 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text F3:Company 
    vTcl:DefineAlias "$site_3_0.but92" "Button11" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but112 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ff0000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text N:Manage 
    vTcl:DefineAlias "$site_3_0.but112" "Button15" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but114 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ff0000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Rental 
    vTcl:DefineAlias "$site_3_0.but114" "Button16" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but115 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #ff0000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text License 
    vTcl:DefineAlias "$site_3_0.but115" "Button17" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but91 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -width 127 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but92 \
        -in $site_3_0 -x 0 -relx 0.068 -y 0 -rely 0.047 -width 127 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but112 \
        -in $site_3_0 -x 0 -relx 0.132 -y 0 -rely 0.806 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but114 \
        -in $site_3_0 -x 0 -relx 0.126 -y 0 -rely 0.837 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but115 \
        -in $site_3_0 -x 0 -relx 0.132 -y 0 -rely 0.869 -width 77 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra51 \
        -borderwidth 2 -relief groove -background #ffffff -height 655 \
        -highlightbackground #400040 -width 637 
    vTcl:DefineAlias "$top.fra51" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra55 \
        -borderwidth 2 -relief groove -background #d9ffff -height 525 \
        -width 388 
    vTcl:DefineAlias "$top.fra55" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra55
    frame $site_3_0.fra56 \
        -borderwidth 2 -relief groove -background #0433d5 -height 35 \
        -width 405 
    vTcl:DefineAlias "$site_3_0.fra56" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra56
    label $site_4_0.lab95 \
        -activeforeground SystemButtonText -anchor w -background #0433d5 \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -text {Account Books} 
    vTcl:DefineAlias "$site_4_0.lab95" "Label11" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab95 \
        -in $site_4_0 -x 0 -relx 0.37 -y 0 -rely 0.286 -width 0 \
        -relwidth 0.306 -height 0 -relheight 0.6 -anchor nw \
        -bordermode ignore 
    label $site_3_0.lab96 \
        -activeforeground SystemButtonText -anchor w -background #d9ffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text SUMMARY 
    vTcl:DefineAlias "$site_3_0.lab96" "Label12" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but97 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Cash/Bank Book(s)} 
    vTcl:DefineAlias "$site_3_0.but97" "Button12" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but98 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9ffff \
        -highlightcolor black -pady 0 -text Ledger 
    vTcl:DefineAlias "$site_3_0.but98" "Button13" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but99 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Group Vouchers} 
    vTcl:DefineAlias "$site_3_0.but99" "Button14" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab100 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background #d9ffff -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Light} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text REGISTERS 
    vTcl:DefineAlias "$site_3_0.lab100" "Label12_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but101 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {ConTra Registers
} 
    vTcl:DefineAlias "$site_3_0.but101" "Button12_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but102 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {PaYment Register} 
    vTcl:DefineAlias "$site_3_0.but102" "Button12_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but103 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Receipt Register} 
    vTcl:DefineAlias "$site_3_0.but103" "Button12_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but104 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Sales Register} 
    vTcl:DefineAlias "$site_3_0.but104" "Button12_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but105 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Purchase Register} 
    vTcl:DefineAlias "$site_3_0.but105" "Button12_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but106 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Journal Register} 
    vTcl:DefineAlias "$site_3_0.but106" "Button12_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but107 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Debit Note Register} 
    vTcl:DefineAlias "$site_3_0.but107" "Button12_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but108 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {CrEdit Note Register} 
    vTcl:DefineAlias "$site_3_0.but108" "Button12_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but109 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Quit 
    vTcl:DefineAlias "$site_3_0.but109" "Button12_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but116 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #d9ffff -borderwidth 0 -compound left \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {VoUcher Clarification} 
    vTcl:DefineAlias "$site_3_0.but116" "Button18" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra56 \
        -in $site_3_0 -x 0 -relx -0.026 -y 0 -rely -0.02 -width 0 \
        -relwidth 1.044 -height 0 -relheight 0.069 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab96 \
        -in $site_3_0 -x 0 -relx 0.309 -y 0 -rely 0.114 -width 0 \
        -relwidth 0.191 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but97 \
        -in $site_3_0 -x 0 -relx 0.155 -y 0 -rely 0.171 -width 227 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but98 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.209 -width 247 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but99 \
        -in $site_3_0 -x 0 -relx 0.129 -y 0 -rely 0.247 -width 237 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab100 \
        -in $site_3_0 -x 0 -relx 0.309 -y 0 -rely 0.285 -width 0 \
        -relwidth 0.268 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but101 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.361 -width 327 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but102 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.399 -width 327 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but103 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.437 -width 297 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but104 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.513 -width 307 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but105 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.551 -width 307 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but106 \
        -in $site_3_0 -x 0 -relx 0.129 -y 0 -rely 0.627 -width 237 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but107 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.665 -width 317 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but108 \
        -in $site_3_0 -x 0 -relx 0.052 -y 0 -rely 0.703 -width 317 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but109 \
        -in $site_3_0 -x 0 -relx 0.103 -y 0 -rely 0.913 -width 197 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but116 \
        -in $site_3_0 -x 0 -relx 0.258 -y 0 -rely 0.798 -width 167 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra57 \
        -borderwidth 2 -relief groove -background #ffffff -height 643 \
        -width 613 
    vTcl:DefineAlias "$top.fra57" "Frame7" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra57
    frame $site_3_0.fra58 \
        -borderwidth 2 -relief groove -background #ffffff -height 132 \
        -width -15 
    vTcl:DefineAlias "$site_3_0.fra58" "Frame8" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra58
    label $site_4_0.lab61 \
        -activeforeground #000000 -anchor w -background #ffffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Malgun Gothic Semilight} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text {CURRENT DATE
} 
    vTcl:DefineAlias "$site_4_0.lab61" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab62 \
        -activeforeground SystemButtonText -anchor w -background #ffffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Malgun Gothic Semilight} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text {CURRENT PERIOD} 
    vTcl:DefineAlias "$site_4_0.lab62" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab61 \
        -in $site_4_0 -x 0 -relx 0.829 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.156 -height 0 -relheight 0.474 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab62 \
        -in $site_4_0 -x 0 -relx 0.017 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.189 -height 0 -relheight 0.326 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra59 \
        -borderwidth 2 -relief groove -background #ffffff -height 25 \
        -highlightcolor #8080ff -width 604 
    vTcl:DefineAlias "$site_3_0.fra59" "Frame9" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra60 \
        -borderwidth 2 -relief groove -background #ffffff -height 15 \
        -width 624 
    vTcl:DefineAlias "$site_3_0.fra60" "Frame10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activeforeground SystemButtonText -anchor w -background #ffffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Malgun Gothic Semilight} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text {NAME OF COMPANY} 
    vTcl:DefineAlias "$site_3_0.lab63" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -activeforeground SystemButtonText -anchor w -background #ffffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Malgun Gothic Semilight} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text {DATE OF LAST ENTRY} 
    vTcl:DefineAlias "$site_3_0.lab64" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text GOLD 
    vTcl:DefineAlias "$site_3_0.lab77" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab93 \
        -activeforeground SystemButtonText -anchor w -background #ffffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Malgun Gothic Semilight} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text {CURRENT DATE} 
    vTcl:DefineAlias "$site_3_0.lab93" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab94 \
        -activeforeground SystemButtonText -anchor w -background #ffffff \
        -compound left -disabledforeground #a3a3a3 \
        -font {-family {Malgun Gothic Semilight} -size 8 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #0000ff -text {CURRENT PERIOD} 
    vTcl:DefineAlias "$site_3_0.lab94" "Label10" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra58 \
        -in $site_3_0 -x 0 -relx 1.26 -y 0 -rely -0.065 -width 0 \
        -relwidth 0.002 -height 0 -relheight 0.215 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra59 \
        -in $site_3_0 -x 0 -y 0 -rely 0.142 -width 0 -relwidth 1.002 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $site_3_0.fra60 \
        -in $site_3_0 -x 0 -relx -0.017 -y 0 -rely 0.995 -width 0 \
        -relwidth 1.037 -height 0 -relheight 0.024 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.143 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.748 -y 0 -rely 0.159 -width 0 \
        -relwidth 0.204 -height 0 -relheight 0.017 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.216 -y 0 -rely -0.111 -width 0 \
        -relwidth 0.255 -height 0 -relheight 0.082 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 0 -relx 0.796 -y 0 -rely 0.031 -width 0 \
        -relwidth 0.154 -height 0 -relheight 0.033 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab94 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.016 -width 0 \
        -relwidth 0.206 -height 0 -relheight 0.05 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.01 -height 0 -relheight 0.092 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx -0.007 -y 0 -rely 0.085 -width 0 -relwidth 1.015 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -relx 0.886 -y 0 -rely 0.113 -width 0 -relwidth 0.116 \
        -height 0 -relheight 0.898 -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -relx 0.439 -y 0 -rely 0.113 -width 0 -relwidth 0.466 \
        -height 0 -relheight 0.929 -anchor nw -bordermode ignore 
    place $top.fra55 \
        -in $top -x 0 -relx 0.527 -y 0 -rely 0.199 -width 0 -relwidth 0.284 \
        -height 0 -relheight 0.746 -anchor nw -bordermode ignore 
    place $top.fra57 \
        -in $top -x 0 -relx -0.007 -y 0 -rely 0.113 -width 0 -relwidth 0.449 \
        -height 0 -relheight 0.912 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

